In [2]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])

print("Array a:", a)
print("Shape of a:", a.shape)
print("Data type of a:", a.dtype)
print("Number of dimensions of a:", a.ndim)
print("Item size in bytes of a:", a.itemsize)

Array a: [1 2 3 4 5]
Shape of a: (5,)
Data type of a: int64
Number of dimensions of a: 1
Item size in bytes of a: 8


In [3]:
print("zeros:\n", np.zeros((2, 3)))
print("\nones:\n", np.ones((2, 3)))
print("\nfull:\n", np.full((2, 3), 7))
print("\narange:", np.arange(0, 10, 2))
print("linspace:", np.linspace(0, 1, 5))


zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

full:
 [[7 7 7]
 [7 7 7]]

arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]
